[project]
name = "app"
version = "0.1.0"
description = "SMS SENDER"
readme = "README.md"
requires-python = ">=3.11.9"
dependencies = []

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
